import '../styles/globals.css'
import { ThemeProvider } from '../components/ThemeProvider'

export const metadata = {
  title: 'GunHyuk',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
